import java.awt.Color;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juanita
 */
public class CarFrameForme extends javax.swing.JFrame {
 
    /**
     * Creates new form CarFrameForme
     */
    public CarFrameForme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBrake = new javax.swing.JButton();
        jLabelAccelatareMessage = new javax.swing.JLabel();
        jButtonAccelarate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelModelTe = new javax.swing.JLabel();
        jLabel6ColorCopy = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jLabelModelCopy = new javax.swing.JLabel();
        jLabelMakeCopy = new javax.swing.JLabel();
        jLabelColorCopy = new javax.swing.JLabel();
        jLabel1YearCopy = new javax.swing.JLabel();
        jLabelMakeTe = new javax.swing.JLabel();
        jLabel1MarkCopy = new javax.swing.JLabel();
        jLabel1ModelCopy = new javax.swing.JLabel();
        jLabelYearTe = new javax.swing.JLabel();
        jLabelYearCopy = new javax.swing.JLabel();
        jLabelColorTe = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxColor = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jComboBoxMake = new javax.swing.JComboBox<>();
        jComboBoxModel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonBrake.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBrake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBrake.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBrake.setText("Brake");
        jButtonBrake.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrakeActionPerformed(evt);
            }
        });

        jLabelAccelatareMessage.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelAccelatareMessage.setForeground(new java.awt.Color(153, 0, 0));
        jLabelAccelatareMessage.setText("0");

        jButtonAccelarate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAccelarate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAccelarate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAccelarate.setText("Speed");
        jButtonAccelarate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonAccelarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccelarateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAccelarate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAccelatareMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelAccelatareMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAccelarate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Car Accelarator ");

        jLabelModelTe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelModelTe.setText("Model:");

        jLabel6ColorCopy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6ColorCopy.setText("Color:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Create Car");

        jButtonStart.setBackground(new java.awt.Color(0, 0, 0));
        jButtonStart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonStart.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStart.setText("Start");
        jButtonStart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jLabelModelCopy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelModelCopy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMakeCopy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMakeCopy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelMakeCopy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelColorCopy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelColorCopy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1YearCopy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1YearCopy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMakeTe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMakeTe.setText("Make:");

        jLabel1MarkCopy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1MarkCopy.setText("Make:");

        jLabel1ModelCopy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1ModelCopy.setText("Model:");

        jLabelYearTe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelYearTe.setText("Year:");

        jLabelYearCopy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelYearCopy.setText("Year:");

        jLabelColorTe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelColorTe.setText("Color:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("My Car");

        jComboBoxColor.setEditable(true);
        jComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Black", "Blue", "Pink", " ", " " }));
        jComboBoxColor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxColorPropertyChange(evt);
            }
        });

        jComboBoxYear.setEditable(true);
        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2014", "2015", "2016", "2017", "2018" }));

        jComboBoxMake.setEditable(true);
        jComboBoxMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toya", "Niss", "Jeep", "Cheky", " " }));

        jComboBoxModel.setEditable(true);
        jComboBoxModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LT-4", "TE-90", "Gold-xd", "OMEGA-89", "TX-Mobile" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMakeTe)
                                    .addComponent(jLabelModelTe)
                                    .addComponent(jLabelYearTe)
                                    .addComponent(jLabelColorTe))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                        .addComponent(jComboBoxColor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxMake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(102, 102, 102)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1MarkCopy)
                                    .addComponent(jLabelYearCopy)
                                    .addComponent(jLabel1ModelCopy)
                                    .addComponent(jLabel6ColorCopy))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelModelCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMakeCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1YearCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelColorCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1MarkCopy)
                                    .addComponent(jLabelMakeCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelModelCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1ModelCopy))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelYearCopy)
                                    .addComponent(jLabel1YearCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6ColorCopy)
                                    .addComponent(jLabelColorCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMakeTe)
                                    .addComponent(jComboBoxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelModelTe)
                                    .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelYearTe)
                                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelColorTe)
                                    .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowActivated

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed

        // Try Catch Staments
        // Author Name: Juana Rodriguez
        // Pourpose: This try Catch is to reduce the erros 
        // 
        try
        {       
            // Porpose: Make new variables to create object and assignet to myCar
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            String make = (String) this.jComboBoxMake.getSelectedItem();
            String model = (String)this.jComboBoxModel.getSelectedItem();
            String color = (String) this.jComboBoxColor.getSelectedItem();          
            String Year = (String) this.jComboBoxYear.getSelectedItem();
            
            //Pourpose: Create an Car object and assign it to myAccount
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            Car myCar = new Car(make, model, color ,(Integer.parseInt(Year)) );
            
            // Purpose: Get the choice of the user and assign it to the
            // variable myMake
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017           
            String myMake = myCar.getMake();
            // Purpose: This will assign the choice of the user to the jLebelMakeCopy
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            this.jLabelMakeCopy.setText(myMake);
            
            // Purpose: Get the choice of the user and assign it to the
            // variable myModel
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            String myModel = myCar.getModel();
            // Purpose: This will assign the choice of the user to the jLebelModelCopy
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            this.jLabelModelCopy.setText(myModel);                                               
            // Purpose: Get the choice of the user and assign it to the
            // variable myYear
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            int myYear = myCar.getYearModel();
            // Purpose: This will assign the choice of the user to the jLebelYearCopy
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            this.jLabel1YearCopy.setText(Integer.toString(myYear));
            // Purpose: Get the choice of the user and assign it to the
            // variable mycolor
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            String mycolor = myCar.getColor();
            // Purpose: This will assign the choice of the user to the jLebelColorCopy
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            this.jLabelColorCopy.setText(mycolor);
            // Name If Stament: if else if Stament
            // Author Name: Juana Rodriguez
            // Purpose: This if Stament will let the user to choice from a few colors
            // and make the background of the jPanel1 red, pink, ect.
            if(color.equals("Red"))
            {
                // Class Name: Color
                // Purpose: set the jPanrl1's background to red
                // Author name: Juana Rodriguez
                this.jPanel1.setBackground(Color.red);
                
            }
            else if (color.equals("Pink"))
            {
                // Class Name: Color
                // Purpose: set the jPanrl1's background to pink
                // Author name: Juana Rodriguez
                this.jPanel1.setBackground(Color.PINK);
            }
            else if (color.equals("Green"))
            {
                // Class Name: Color
                // Purpose: set the jPanrl1's background to green
                // Author name: Juana Rodriguez
                this.jPanel1.setBackground(Color.GREEN);
            }
            
            else if (color.equals("Black"))
            {
                // Class Name: Color
                // Purpose: set the jPanrl1's background to black
                // Author name: Juana Rodriguez
                this.jPanel1.setBackground(Color.BLACK);
                this.jButtonAccelarate.setBackground(Color.DARK_GRAY);
                this.jButtonBrake.setBackground(Color.DARK_GRAY);
            }
            //Author Name: Juana Rodriguez
            // Purpose: Sets the 0 as the start speed in the jLabelAccelatareMessage label
            this.jLabelAccelatareMessage.setText(Integer.toString(0));
            
            // Purpose: Enabled jComboBoxColor, jComboBoxMake, jComboBoxModel, jComboBoxYear, 
            //jLabel7 so the user don't change the original choices 
            this.jComboBoxColor.setEnabled(false);
            this.jComboBoxMake.setEnabled(false);
            this.jComboBoxModel.setEnabled(false);
            this.jComboBoxYear.setEnabled(false);
            this.jLabel7.setEnabled(false);
            
        }       
        catch (Exception e)
        {
            // Purpose: Get a error message
            // AuthorName: Juana Rodriguez
            JOptionPane.showMessageDialog(this, "Enter a valid Input!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
     
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonAccelarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccelarateActionPerformed
        try
        {     
            // Porpose: Make new variables to create object and assignet to myCar
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            String make = (String) this.jComboBoxMake.getSelectedItem();
            String model = (String)this.jComboBoxModel.getSelectedItem();
            String color = (String) this.jComboBoxColor.getSelectedItem();           
            String Year = (String) this.jComboBoxYear.getSelectedItem();
            String stringSpeed = this.jLabelAccelatareMessage.getText();
            //Pourpose: Create an Car object and assign it to myAccount
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            Car myCar = new Car(make, model, color ,(Integer.parseInt(Year)) );
            // Purpose: converts the stringSpeed into string
            // Author Name: Juana Rodriguez
            // Date: 9/17/2017
            int oldSpeed = Integer.parseInt(stringSpeed);
            // Purpose: set the speed
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            myCar.setSpeed(oldSpeed);
            // Call the aceelarate from the car class
            // Class name: Juana Rodriguez
            int accelarate = myCar.accelerate();
            // Purpose: se the text in the jLabelAccelatareMessage
            this.jLabelAccelatareMessage.setText(Integer.toString(accelarate));
            // if Name: if Stament
            // Purpose: if the user reach to 200 a message will be display
            // Authoe Name: Juana Rodriguez
            // Date: 9/17/2017
            if(oldSpeed == 200)
            {
                // Display a JOptionpane Message 
                JOptionPane.showMessageDialog(this, "You reach the MAXIMUN speed go down!!", "Warning", JOptionPane.ERROR_MESSAGE);
            }                        
            this.jButtonStart.setEnabled(false);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Enter a Invalid Input!!", "Error", JOptionPane.ERROR_MESSAGE);
               
        }
    }//GEN-LAST:event_jButtonAccelarateActionPerformed

    private void jButtonBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrakeActionPerformed
        
        try
        {
            // Purpose: Make new variables to create object and assignet to myCar
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            String make = (String) this.jComboBoxMake.getSelectedItem();
            String model = (String)this.jComboBoxModel.getSelectedItem();
            String color = (String) this.jComboBoxColor.getSelectedItem();
            String Year = (String) this.jComboBoxYear.getSelectedItem();
            String stringSpeed = this.jLabelAccelatareMessage.getText();
            //Pourpose: Create an Car object and assign it to myAccount
            // Author Name: Juana Rodriguez
            // Date: 9/18/2017
            Car myCar = new Car(make, model, color ,(Integer.parseInt(Year)));
            // Purpose: converts the stringSpeed into string
            // Author Name: Juana Rodriguez
            // Date: 9/17/2017
            int oldSpeed = Integer.parseInt(stringSpeed);
            // Purpose: set the speed
            // Author Name: Juana Rodriguez
            // Date: 9/19/2017
            myCar.setSpeed(oldSpeed);
            // Call the aceelarate from the car class
            // Class name: Juana Rodriguez
            // Date: 9/17/2017, 9/20/2017
            int brake = myCar.brake();
            this.jLabelAccelatareMessage.setText(Integer.toString(brake));
            // if Name: if Stament
            // Purpose: if the user reach 0 a message will be display
            // Authoe Name: Juana Rodriguez
            // Date: 9/17/2017, 2/18/2017
            if(oldSpeed == 0)
            {
                // Display a JOptionpane Message 
                JOptionPane.showMessageDialog(this, "You reach the MINIMUM speed go up!!", "Warning", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, "Enter a Invalid Input!!", "Error", JOptionPane.ERROR_MESSAGE);
           return;
        }                   
    }//GEN-LAST:event_jButtonBrakeActionPerformed

    private void jComboBoxColorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxColorPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBoxColorPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarFrameForme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarFrameForme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarFrameForme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarFrameForme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarFrameForme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccelarate;
    private javax.swing.JButton jButtonBrake;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JComboBox<String> jComboBoxColor;
    private javax.swing.JComboBox<String> jComboBoxMake;
    private javax.swing.JComboBox<String> jComboBoxModel;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1MarkCopy;
    private javax.swing.JLabel jLabel1ModelCopy;
    private javax.swing.JLabel jLabel1YearCopy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6ColorCopy;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAccelatareMessage;
    private javax.swing.JLabel jLabelColorCopy;
    private javax.swing.JLabel jLabelColorTe;
    private javax.swing.JLabel jLabelMakeCopy;
    private javax.swing.JLabel jLabelMakeTe;
    private javax.swing.JLabel jLabelModelCopy;
    private javax.swing.JLabel jLabelModelTe;
    private javax.swing.JLabel jLabelYearCopy;
    private javax.swing.JLabel jLabelYearTe;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
